version: '2'
services:
    zookeeper1:
        image: registry-internal.cn-hangzhou.aliyuncs.com/distributed/zookeeper:3.4.9
        restart: always
        container_name: zookeeper1
        ports:
            - "2181:2181"
        environment:
            SERVER_ID: 1
            ZK_SERVERS: server.1=zookeeper1:2888:3888 server.2=zookeeper2:2888:3888 server.3=zookeeper3:2888:3888

    zookeeper2:
        image: registry-internal.cn-hangzhou.aliyuncs.com/distributed/zookeeper:3.4.9
        restart: always
        container_name: zookeeper2
        ports:
            - "2182:2181"
        environment:
            SERVER_ID: 2
            ZK_SERVERS: server.1=zookeeper1:2888:3888 server.2=zookeeper2:2888:3888 server.3=zookeeper3:2888:3888

    zookeeper3:
        image: registry-internal.cn-hangzhou.aliyuncs.com/distributed/zookeeper:3.4.9
        restart: always
        container_name: zookeeper3
        ports:
            - "2183:2181"
        environment:
            SERVER_ID: 3
            ZK_SERVERS: server.1=zookeeper1:2888:3888 server.2=zookeeper2:2888:3888 server.3=zookeeper3:2888:3888